language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: IwzTfV7vwF8R3fDPrITEjtPcmAUAQOK0d+BeLrMh5mzw3eIT0VQuF+r5hYn41BW3de6wizDUlq1qSR9MptbmQKPQgOqqBdw0JaWdROJQ694eJwTwNjmeQYnkgatmjRXfUu+6MGvsbkGnLODeWdRLZiIVkjxSX9Qu2+YsKdiqV2zUg4RgF+UBMmfdLJQC+95gHfu04FVcta6QF5R6qzcKGnW6FffyhFQdyJ5xCm073wYXsFw9hBG8j4TGQDJzdhafFBEcDheTaMSJmG6pAUwPsCeAWg1lVcyCw6x26vk+HRGtwqECcgoSpvUnB0/sVMAHRqzUHI7xl7eUujKx8keMptQrTwORLRkhyKfFmHgs2xXRl3RkZN8NC/TN13S5GnhidMeHfsVYrW7nD/8vlnLW9+nQ5OkfvXBVqs5zAG8TjSojUgVSjrO5vtb/3p+YUTOtjayAG0ZSL4+err+0TlTXrqzUM1FyLHDDcElxT8Lx3RsE373AwPBqYPc3CeJqd4HPCGoRUADcf1Vu+2mSKP4q7Js7JLyCQWTK89tp34vvmjYmTIJ3mqX7+shHo8WD2RW0x0nu789CrYhMZfY9jhyonKXmObuXR75m5qiZLvym3viEyVGawiChgH7xLQULNU7lAj57XmmHB5L1jyvvHHHpG8WtBHaX5m1eN2xNU7f63z8=
  app: aqueous-river-81513
  on:
    repo: thinkful-c11/blog-app-mongoose-challenge-solution
